language: python

python:
 - 3.6

install: pip install -r requirements.txt

script:
 - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then python -m unittest discover; fi
after_success:
 - coverage report
 - coveralls
notifications:
  email: 
    - dvdssali@gmail.com
